BASE <http://iec.ch/TC57/2013/CIM-schema-cim16#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX cim: <http://iec.ch/TC57/2013/CIM-schema-cim16#>
PREFIX entsoe: <http://entsoe.eu/CIM/SchemaExtension/3/1#>

WITH <urn:uuid:2399cbd2-9a39-11e0-aa80-0800200c9a66_EU>
DELETE {
	<urn:uuid:046adf51-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "2-12_0" ;
		<Terminal.ConductingEquipment> <urn:uuid:045a3d89-c766-11e1-8775-005056c00008> .

	<urn:uuid:046fe868-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "2-12_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:045a3d89-c766-11e1-8775-005056c00008> .

	<urn:uuid:044ef2e9-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "1-3_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:04535fb7-c766-11e1-8775-005056c00008> .

	<urn:uuid:047c4474-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "1-3_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:04535fb7-c766-11e1-8775-005056c00008> .

	<urn:uuid:04720b4a-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "6-7_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:045c8776-c766-11e1-8775-005056c00008> .

	<urn:uuid:046efe08-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "6-7_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:045c8776-c766-11e1-8775-005056c00008> .

	<urn:uuid:0476c633-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "5-11_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:047f78c2-c766-11e1-8775-005056c00008> .

	<urn:uuid:045bc426-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "5-11_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:047f78c2-c766-11e1-8775-005056c00008> .

	<urn:uuid:04801506-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "8-30_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:0483be84-c766-11e1-8775-005056c00008> .

	<urn:uuid:0454e651-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "8-30_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:0483be84-c766-11e1-8775-005056c00008> .

	<urn:uuid:0455d0b2-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "5-6_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:044b9789-c766-11e1-8775-005056c00008> .

	<urn:uuid:044a5f01-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "5-6_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:044b9789-c766-11e1-8775-005056c00008> .

	<urn:uuid:044b9786-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "1-2_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:048963d9-c766-11e1-8775-005056c00008> .

	<urn:uuid:04845acb-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "1-2_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:048963d9-c766-11e1-8775-005056c00008> .

	<urn:uuid:04880440-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "11-12_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:0484f709-c766-11e1-8775-005056c00008> .

	<urn:uuid:0456e227-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "11-12_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:0484f709-c766-11e1-8775-005056c00008> .

	<urn:uuid:04745535-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "8-9_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:044bbe91-c766-11e1-8775-005056c00008> .

	<urn:uuid:048a7548-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "8-9_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:044bbe91-c766-11e1-8775-005056c00008> .

	<urn:uuid:04614262-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "9-10_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:044a5f09-c766-11e1-8775-005056c00008> .

	<urn:uuid:04834957-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "9-10_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:044a5f09-c766-11e1-8775-005056c00008> .

	<urn:uuid:0485452a-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "11-13_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:04553477-c766-11e1-8775-005056c00008> .

	<urn:uuid:0479fa89-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "11-13_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:04553477-c766-11e1-8775-005056c00008> .

	<urn:uuid:0477feb7-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "7-12_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:0474a358-c766-11e1-8775-005056c00008> .

	<urn:uuid:046ab848-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "7-12_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:0474a358-c766-11e1-8775-005056c00008> .

	<urn:uuid:04742e24-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "3-5_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:0468e382-c766-11e1-8775-005056c00008> .

	<urn:uuid:046b0668-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "3-5_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:0468e382-c766-11e1-8775-005056c00008> .

	<urn:uuid:047a48a1-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "3-12_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:045ed162-c766-11e1-8775-005056c00008> .

	<urn:uuid:047b5a14-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "3-12_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:045ed162-c766-11e1-8775-005056c00008> .

	<urn:uuid:04529c66-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "4-5_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:04614263-c766-11e1-8775-005056c00008> .

	<urn:uuid:04753f92-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "4-5_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:04614263-c766-11e1-8775-005056c00008> .

	<urn:uuid:0455f7c5-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "4-11_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:04642896-c766-11e1-8775-005056c00008> .

	<urn:uuid:04803c17-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "4-11_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:04642896-c766-11e1-8775-005056c00008> .

	<urn:uuid:04745533-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "8-5_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:04575750-c766-11e1-8775-005056c00008> .

	<urn:uuid:046b2d74-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "8-5_1" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "2" ;
		<Terminal.ConductingEquipment> <urn:uuid:04575750-c766-11e1-8775-005056c00008> .

	<urn:uuid:045b7606-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "Breed SM_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:045868c0-c766-11e1-8775-005056c00008> .

	<urn:uuid:045e8340-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "Olive SC_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:0447c6f6-c766-11e1-8775-005056c00008> .

	<urn:uuid:047d7cf3-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "HickryCk LD_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:044a5f08-c766-11e1-8775-005056c00008> .

	<urn:uuid:04731cb7-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "NwCarlsl NegG LD_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:0447ee05-c766-11e1-8775-005056c00008> .

	<urn:uuid:047e6758-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "Kankakee LD_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:044ea4c0-c766-11e1-8775-005056c00008> .

	<urn:uuid:04522734-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "SouthBnd LD_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:048b5fa5-c766-11e1-8775-005056c00008> .

	<urn:uuid:048433b8-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "Olive NegG LD_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:04867dab-c766-11e1-8775-005056c00008> .

	<urn:uuid:0462c902-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "Pokagon LD_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:0485e168-c766-11e1-8775-005056c00008> .

	<urn:uuid:0476ed4b-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "Riversde LD_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:045645e2-c766-11e1-8775-005056c00008> .

	<urn:uuid:046c8d06-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "JacksnRd LD_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:046a4319-c766-11e1-8775-005056c00008> .

	<urn:uuid:044c0cb9-c766-11e1-8775-005056c00008> rdf:type <Terminal> ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "NwCarlsl LD_0" ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.sequenceNumber> "1" ;
		<Terminal.ConductingEquipment> <urn:uuid:047a48a8-c766-11e1-8775-005056c00008> .

	<urn:uuid:044a5f08-c766-11e1-8775-005056c00008> rdf:type <EnergyConsumer> ;
		<EnergyConsumer.p> "39" ;
		<EnergyConsumer.q> "10" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "HickryCk LD" ;
		<Equipment.EquipmentContainer> <urn:uuid:047eb579-c766-11e1-8775-005056c00008> .

	<urn:uuid:0447ee05-c766-11e1-8775-005056c00008> rdf:type <EnergyConsumer> ;
		<EnergyConsumer.p> "9" ;
		<EnergyConsumer.q> "0" ;
		<IdentifiedObject.name> "NwCarlsl NegG LD" ;
		<Equipment.aggregate> "false" ;
		<EnergyConsumer.LoadResponse> <urn:uuid:62b0f284-310d-4b24-b3e9-de366f5d0ee0> ;
		<Equipment.EquipmentContainer> <urn:uuid:048a9c58-c766-11e1-8775-005056c00008> .

	<urn:uuid:044ea4c0-c766-11e1-8775-005056c00008> rdf:type <EnergyConsumer> ;
		<EnergyConsumer.p> "52" ;
		<EnergyConsumer.q> "22" ;
		<IdentifiedObject.name> "Kankakee LD" ;
		<Equipment.aggregate> "false" ;
		<Equipment.EquipmentContainer> <urn:uuid:044f6818-c766-11e1-8775-005056c00008> .

	<urn:uuid:048b5fa5-c766-11e1-8775-005056c00008> rdf:type <EnergyConsumer> ;
		<EnergyConsumer.p> "70" ;
		<EnergyConsumer.q> "23" ;
		<IdentifiedObject.name> "SouthBnd LD" ;
		<Equipment.aggregate> "false" ;
		<Equipment.EquipmentContainer> <urn:uuid:04605807-c766-11e1-8775-005056c00008> .

	<urn:uuid:04867dab-c766-11e1-8775-005056c00008> rdf:type <EnergyConsumer> ;
		<EnergyConsumer.p> "28" ;
		<EnergyConsumer.q> "0" ;
		<IdentifiedObject.name> "Olive NegG LD" ;
		<Equipment.aggregate> "false" ;
		<EnergyConsumer.LoadResponse> <urn:uuid:9f54ecca-3b0d-4b55-8bce-9f0eb76bde1b> ;
		<Equipment.EquipmentContainer> <urn:uuid:047d07c9-c766-11e1-8775-005056c00008> .

	<urn:uuid:0485e168-c766-11e1-8775-005056c00008> rdf:type <EnergyConsumer> ;
		<EnergyConsumer.p> "20" ;
		<EnergyConsumer.q> "9" ;
		<IdentifiedObject.name> "Pokagon LD" ;
		<Equipment.aggregate> "false" ;
		<Equipment.EquipmentContainer> <urn:uuid:045d4ac5-c766-11e1-8775-005056c00008> .

	<urn:uuid:045645e2-c766-11e1-8775-005056c00008> rdf:type <EnergyConsumer> ;
		<EnergyConsumer.p> "51" ;
		<EnergyConsumer.q> "27" ;
		<IdentifiedObject.name> "Riversde LD" ;
		<Equipment.aggregate> "false" ;
		<Equipment.EquipmentContainer> <urn:uuid:0488c79a-c766-11e1-8775-005056c00008> .

	<urn:uuid:046a4319-c766-11e1-8775-005056c00008> rdf:type <EnergyConsumer> ;
		<EnergyConsumer.p> "19" ;
		<EnergyConsumer.q> "2" ;
		<IdentifiedObject.name> "JacksnRd LD" ;
		<Equipment.aggregate> "false" ;
		<Equipment.EquipmentContainer> <urn:uuid:047eb571-c766-11e1-8775-005056c00008> .

	<urn:uuid:047a48a8-c766-11e1-8775-005056c00008> rdf:type <EnergyConsumer> ;
		<EnergyConsumer.p> "30" ;
		<EnergyConsumer.q> "12" ;
		<IdentifiedObject.name> "NwCarlsl LD" ;
		<Equipment.aggregate> "false" ;
		<Equipment.EquipmentContainer> <urn:uuid:048a9c58-c766-11e1-8775-005056c00008> .

	<urn:uuid:f26d4eb3-ebdb-4025-8080-f856ce656b42> rdf:type <ThermalGeneratingUnit> ;
		<GeneratingUnit.initialP> "450" ;
		<GeneratingUnit.maxOperatingP> "600" ;
		<GeneratingUnit.minOperatingP> "300" ;
		<GeneratingUnit.normalPF> "0" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "Breed SM" ;
		<Equipment.EquipmentContainer> <urn:uuid:046030f9-c766-11e1-8775-005056c00008> .

	<urn:uuid:045868c0-c766-11e1-8775-005056c00008> rdf:type <SynchronousMachine> ;
		<SynchronousMachine.earthing> "false" ;
		<SynchronousMachine.maxQ> "640" ;
		<SynchronousMachine.minQ> "-225" ;
		<SynchronousMachine.qPercent> "100" ;
		<SynchronousMachine.r0> "0" ;
		<SynchronousMachine.r2> "0" ;
		<SynchronousMachine.referencePriority> "0" ;
		<SynchronousMachine.satDirectSubtransX> "0" ;
		<SynchronousMachine.type> "generator" ;
		<SynchronousMachine.r> "0" ;
		<SynchronousMachine.x0> "0" ;
		<SynchronousMachine.x2> "0" ;
		<SynchronousMachine.operatingMode> "generator" ;
		<RotatingMachine.ratedPowerFactor> "0.8" ;
		<RotatingMachine.ratedS> "750" ;
		<RotatingMachine.p> "-450" ;
		<RotatingMachine.q> "0" ;
		<RegulatingCondEq.controlEnabled> "true" ;
		<IdentifiedObject.name> "Breed SM" ;
		<RotatingMachine.GeneratingUnit> <urn:uuid:f26d4eb3-ebdb-4025-8080-f856ce656b42> ;
		<RegulatingCondEq.RegulatingControl> <urn:uuid:7566f2a7-61eb-42fe-a59a-8276257fdbc6> ;
		<Equipment.EquipmentContainer> <urn:uuid:044f4102-c766-11e1-8775-005056c00008> .

	<urn:uuid:7566f2a7-61eb-42fe-a59a-8276257fdbc6> rdf:type <RegulatingControl> ;
		<RegulatingControl.mode> "voltage" ;
		<RegulatingControl.discrete> "false" ;
		<RegulatingControl.enabled> "true" ;
		<RegulatingControl.targetDeadband> "0" ;
		<RegulatingControl.targetValue> "231" ;
		<RegulatingControl.targetValueUnitMultiplier> "k" ;
		<IdentifiedObject.name> "Breed SM" ;
		<RegulatingControl.Terminal> <urn:uuid:045b7606-c766-11e1-8775-005056c00008> .

	<urn:uuid:045a3d89-c766-11e1-8775-005056c00008> rdf:type <ACLineSegment> ;
		<ACLineSegment.b0ch> "0" ;
		<ACLineSegment.bch> "9.02204E-05" ;
		<ACLineSegment.g0ch> "0" ;
		<ACLineSegment.gch> "0" ;
		<ACLineSegment.r> "3.258288" ;
		<ACLineSegment.r0> "3.323454" ;
		<ACLineSegment.shortCircuitEndTemperature> "80" ;
		<ACLineSegment.x> "10.73318" ;
		<ACLineSegment.x0> "0" ;
		<Conductor.length> "112.0014" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "2-12" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> ;
		<Equipment.EquipmentContainer> <urn:uuid:fed4a332-bf5c-9991-b062-a2721b00b7ad> .

	<urn:uuid:e4248c3c-2067-4389-b657-976913c335e2> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:046adf51-c766-11e1-8775-005056c00008> .

	<urn:uuid:10bd2965-bc7c-4764-a1c7-ae4fda4304ec> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:e4248c3c-2067-4389-b657-976913c335e2> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:09a180b3-124b-4a91-b323-4aad01f45e8a> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1150" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:e4248c3c-2067-4389-b657-976913c335e2> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:6bd63dd1-1344-4183-b7bd-af326919f4eb> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1400" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:e4248c3c-2067-4389-b657-976913c335e2> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:04535fb7-c766-11e1-8775-005056c00008> rdf:type <ACLineSegment> ;
		<ACLineSegment.b0ch> "0" ;
		<ACLineSegment.bch> "6.20983E-05" ;
		<ACLineSegment.g0ch> "0" ;
		<ACLineSegment.gch> "0" ;
		<ACLineSegment.r> "2.247696" ;
		<ACLineSegment.r0> "2.29265" ;
		<ACLineSegment.shortCircuitEndTemperature> "80" ;
		<ACLineSegment.x> "7.387776" ;
		<ACLineSegment.x0> "0" ;
		<Conductor.length> "116.843" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "1-3" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> ;
		<Equipment.EquipmentContainer> <urn:uuid:40678b23-eb91-15cb-dda2-2610e0e019ec> .

	<urn:uuid:548fbf20-161f-4f26-8662-c5059393ffe6> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:044ef2e9-c766-11e1-8775-005056c00008> .

	<urn:uuid:dc37e821-133d-4910-88dd-4cba200d6790> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:548fbf20-161f-4f26-8662-c5059393ffe6> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:bd6a7b7b-b30f-440f-bf3e-7d1d8007b0ab> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1150" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:548fbf20-161f-4f26-8662-c5059393ffe6> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:4ea43e34-67a3-42b8-9601-2189db7790d4> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1400" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:548fbf20-161f-4f26-8662-c5059393ffe6> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:045c8776-c766-11e1-8775-005056c00008> rdf:type <ACLineSegment> ;
		<ACLineSegment.b0ch> "0" ;
		<ACLineSegment.bch> "3.15657E-05" ;
		<ACLineSegment.g0ch> "0" ;
		<ACLineSegment.gch> "0" ;
		<ACLineSegment.r> "0.799762" ;
		<ACLineSegment.r0> "0.8157572" ;
		<ACLineSegment.shortCircuitEndTemperature> "80" ;
		<ACLineSegment.x> "3.624192" ;
		<ACLineSegment.x0> "0" ;
		<Conductor.length> "40.68428" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "6-7" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> ;
		<Equipment.EquipmentContainer> <urn:uuid:f6102a72-48ac-b2b3-322e-5d460755be84> .

	<urn:uuid:7333db74-7101-4ada-a89d-2a04e01f16a6> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:04720b4a-c766-11e1-8775-005056c00008> .

	<urn:uuid:2b72717a-19d8-46aa-9238-3b904a883f1f> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:7333db74-7101-4ada-a89d-2a04e01f16a6> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:ecaca589-8952-4cab-b3dc-f787858d46a9> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1150" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:7333db74-7101-4ada-a89d-2a04e01f16a6> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:361a9cc3-fb33-4037-9b9a-c20adb90b66b> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1400" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:7333db74-7101-4ada-a89d-2a04e01f16a6> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:047f78c2-c766-11e1-8775-005056c00008> rdf:type <ACLineSegment> ;
		<ACLineSegment.b0ch> "0" ;
		<ACLineSegment.bch> "9.97475E-05" ;
		<ACLineSegment.g0ch> "0" ;
		<ACLineSegment.gch> "0" ;
		<ACLineSegment.r> "3.537072" ;
		<ACLineSegment.r0> "3.607813" ;
		<ACLineSegment.shortCircuitEndTemperature> "80" ;
		<ACLineSegment.x> "11.88317" ;
		<ACLineSegment.x0> "0" ;
		<Conductor.length> "63.86811" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "5-11" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> ;
		<Equipment.EquipmentContainer> <urn:uuid:d0ebfe42-1ef9-f555-a8ad-2a9243e1d6eb> .

	<urn:uuid:6634c3a7-488d-4066-9aad-c9e0e8e9f745> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:0476c633-c766-11e1-8775-005056c00008> .

	<urn:uuid:21bc82a8-a636-409c-be97-c68f33f3f239> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:6634c3a7-488d-4066-9aad-c9e0e8e9f745> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:55d07074-4a4b-419b-819d-8d6048fcfd1c> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1150" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:6634c3a7-488d-4066-9aad-c9e0e8e9f745> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:3bc4ab96-7a0d-4e18-b9f5-d89f63a82f0a> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1400" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:6634c3a7-488d-4066-9aad-c9e0e8e9f745> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:0483be84-c766-11e1-8775-005056c00008> rdf:type <ACLineSegment> ;
		<ACLineSegment.b0ch> "0" ;
		<ACLineSegment.bch> "0.001061984" ;
		<ACLineSegment.g0ch> "0" ;
		<ACLineSegment.gch> "0" ;
		<ACLineSegment.r> "2.08604" ;
		<ACLineSegment.r0> "2.127761" ;
		<ACLineSegment.shortCircuitEndTemperature> "80" ;
		<ACLineSegment.x> "24.3936" ;
		<ACLineSegment.x0> "0" ;
		<Conductor.length> "65.43056" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "8-30" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:60ee59f3-5ed7-4551-b623-f4346554b22a> ;
		<Equipment.EquipmentContainer> <urn:uuid:01a32454-1398-54cb-6555-d6d0150f99cd> .

	<urn:uuid:2a5763de-3d99-4411-ab0c-15a1c5780e41> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:04801506-c766-11e1-8775-005056c00008> .

	<urn:uuid:b2f4bbad-bdee-4177-bf98-c89f94114a72> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:2a5763de-3d99-4411-ab0c-15a1c5780e41> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:2e5a9b0c-24d7-4bb6-9761-484be58c5bf6> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1150" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:2a5763de-3d99-4411-ab0c-15a1c5780e41> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:ca795ad3-97e5-4416-aaba-53cce27f6434> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1400" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:2a5763de-3d99-4411-ab0c-15a1c5780e41> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:044b9789-c766-11e1-8775-005056c00008> rdf:type <ACLineSegment> ;
		<ACLineSegment.b0ch> "0" ;
		<ACLineSegment.bch> "8.18411E-05" ;
		<ACLineSegment.g0ch> "0" ;
		<ACLineSegment.gch> "0" ;
		<ACLineSegment.r> "2.073456" ;
		<ACLineSegment.r0> "2.114925" ;
		<ACLineSegment.shortCircuitEndTemperature> "80" ;
		<ACLineSegment.x> "9.40896" ;
		<ACLineSegment.x0> "0" ;
		<Conductor.length> "37.23285" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "5-6" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> ;
		<Equipment.EquipmentContainer> <urn:uuid:9a9901c2-83a4-62e3-94e1-a77c7ff54c64> .

	<urn:uuid:e1c77883-88fe-4a55-9aa2-b1a62a374e04> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:0455d0b2-c766-11e1-8775-005056c00008> .

	<urn:uuid:445e6a38-b9c0-4d6b-a5a2-003055e19b1f> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:e1c77883-88fe-4a55-9aa2-b1a62a374e04> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:3678bd5d-c47e-4eb0-8620-7f9e24a10618> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1150" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:e1c77883-88fe-4a55-9aa2-b1a62a374e04> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:b3b0e81b-a434-4e9c-ad94-1161ff47b077> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1400" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:e1c77883-88fe-4a55-9aa2-b1a62a374e04> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:048963d9-c766-11e1-8775-005056c00008> rdf:type <ACLineSegment> ;
		<ACLineSegment.b0ch> "0" ;
		<ACLineSegment.bch> "0.0001457759" ;
		<ACLineSegment.g0ch> "0" ;
		<ACLineSegment.gch> "0" ;
		<ACLineSegment.r> "5.279472" ;
		<ACLineSegment.r0> "5.385061" ;
		<ACLineSegment.shortCircuitEndTemperature> "80" ;
		<ACLineSegment.x> "17.40658" ;
		<ACLineSegment.x0> "0" ;
		<Conductor.length> "97.14272" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "1-2" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> ;
		<Equipment.EquipmentContainer> <urn:uuid:ed1cb08a-b26d-aba6-a3f4-06301279f2e3> .

	<urn:uuid:9d22a23c-375b-4722-a8c7-467f85a8006d> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:044b9786-c766-11e1-8775-005056c00008> .

	<urn:uuid:f77f5426-5569-43a4-811d-1d55c153484a> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:9d22a23c-375b-4722-a8c7-467f85a8006d> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:ebd82352-16ad-454f-8920-32a110d327d1> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1150" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:9d22a23c-375b-4722-a8c7-467f85a8006d> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:9f39cb45-314c-445e-b177-909854a9ce45> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1400" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:9d22a23c-375b-4722-a8c7-467f85a8006d> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:0484f709-c766-11e1-8775-005056c00008> rdf:type <ACLineSegment> ;
		<ACLineSegment.b0ch> "0" ;
		<ACLineSegment.bch> "2.88108E-05" ;
		<ACLineSegment.g0ch> "0" ;
		<ACLineSegment.gch> "0" ;
		<ACLineSegment.r> "1.036728" ;
		<ACLineSegment.r0> "1.057463" ;
		<ACLineSegment.shortCircuitEndTemperature> "80" ;
		<ACLineSegment.x> "3.415104" ;
		<ACLineSegment.x0> "0" ;
		<Conductor.length> "40.16834" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "11-12" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> ;
		<Equipment.EquipmentContainer> <urn:uuid:29dbf6d0-0a46-9741-fdec-be99f242e5e1> .

	<urn:uuid:2a058307-ead2-4581-9259-f2101bbf3c62> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:04880440-c766-11e1-8775-005056c00008> .

	<urn:uuid:58a288dd-75cf-4be8-bc05-9ccec2c59b20> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:2a058307-ead2-4581-9259-f2101bbf3c62> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:c0261082-5d30-4965-882d-3c1719e82054> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1150" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:2a058307-ead2-4581-9259-f2101bbf3c62> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:70fad3e1-4529-4a7f-9e6c-8ab249d65460> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1400" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:2a058307-ead2-4581-9259-f2101bbf3c62> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:044bbe91-c766-11e1-8775-005056c00008> rdf:type <ACLineSegment> ;
		<ACLineSegment.b0ch> "0" ;
		<ACLineSegment.bch> "0.002400826" ;
		<ACLineSegment.g0ch> "0" ;
		<ACLineSegment.gch> "0" ;
		<ACLineSegment.r> "1.18096" ;
		<ACLineSegment.r0> "1.204579" ;
		<ACLineSegment.shortCircuitEndTemperature> "80" ;
		<ACLineSegment.x> "14.762" ;
		<ACLineSegment.x0> "0" ;
		<Conductor.length> "250.2668" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "8-9" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:60ee59f3-5ed7-4551-b623-f4346554b22a> ;
		<Equipment.EquipmentContainer> <urn:uuid:2c9fd9b1-87fa-d66a-d5fe-c6b9e2924a0f> .

	<urn:uuid:95ca6534-9863-4aa3-98fc-a191ca13973a> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:04745535-c766-11e1-8775-005056c00008> .

	<urn:uuid:4f523cac-c7bd-4c71-ac45-46147cb090ac> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:95ca6534-9863-4aa3-98fc-a191ca13973a> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:0ea6e870-9b01-4226-80d3-5ff1a2f88c40> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1150" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:95ca6534-9863-4aa3-98fc-a191ca13973a> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:205e5d8a-f05a-479d-adaa-3514f48f6857> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1400" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:95ca6534-9863-4aa3-98fc-a191ca13973a> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:044a5f09-c766-11e1-8775-005056c00008> rdf:type <ACLineSegment> ;
		<ACLineSegment.b0ch> "0" ;
		<ACLineSegment.bch> "0.002541322" ;
		<ACLineSegment.g0ch> "0" ;
		<ACLineSegment.gch> "0" ;
		<ACLineSegment.r> "1.24872" ;
		<ACLineSegment.r0> "1.273694" ;
		<ACLineSegment.shortCircuitEndTemperature> "80" ;
		<ACLineSegment.x> "15.5848" ;
		<ACLineSegment.x0> "0" ;
		<Conductor.length> "130.1872" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "9-10" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:60ee59f3-5ed7-4551-b623-f4346554b22a> ;
		<Equipment.EquipmentContainer> <urn:uuid:3e1d2381-2712-7769-e861-0f7505ed2da0> .

	<urn:uuid:0c08daa5-ef97-4cd4-b0a9-79746e43832f> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:04614262-c766-11e1-8775-005056c00008> .

	<urn:uuid:68119708-06ee-4994-9a29-fa2d8f48a646> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:0c08daa5-ef97-4cd4-b0a9-79746e43832f> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:a0202601-e216-4568-ab78-b4fe21fd1fba> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1150" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:0c08daa5-ef97-4cd4-b0a9-79746e43832f> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:b7fac0a3-c5af-48b9-af49-261fd8d46e00> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1400" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:0c08daa5-ef97-4cd4-b0a9-79746e43832f> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:04553477-c766-11e1-8775-005056c00008> rdf:type <ACLineSegment> ;
		<ACLineSegment.b0ch> "0" ;
		<ACLineSegment.bch> "0.0001076676" ;
		<ACLineSegment.g0ch> "0" ;
		<ACLineSegment.gch> "0" ;
		<ACLineSegment.r> "3.87684" ;
		<ACLineSegment.r0> "3.954377" ;
		<ACLineSegment.shortCircuitEndTemperature> "80" ;
		<ACLineSegment.x> "12.73694" ;
		<ACLineSegment.x0> "0" ;
		<Conductor.length> "48.47444" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "11-13" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> ;
		<Equipment.EquipmentContainer> <urn:uuid:c879d0a1-6043-ae0a-7cd4-1639678c30ad> .

	<urn:uuid:6a5b5e9d-b18a-4d87-863f-84eab3075a2d> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:0485452a-c766-11e1-8775-005056c00008> .

	<urn:uuid:140d1ff9-477d-42c6-b93a-31d819ad0b42> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:6a5b5e9d-b18a-4d87-863f-84eab3075a2d> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:7bf0d6eb-6015-4b67-b5f5-7e9417da9602> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1150" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:6a5b5e9d-b18a-4d87-863f-84eab3075a2d> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:efbf8de7-4b84-4834-bb7c-6250b6072211> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1400" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:6a5b5e9d-b18a-4d87-863f-84eab3075a2d> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:0474a358-c766-11e1-8775-005056c00008> rdf:type <ACLineSegment> ;
		<ACLineSegment.b0ch> "0" ;
		<ACLineSegment.bch> "5.01607E-05" ;
		<ACLineSegment.g0ch> "0" ;
		<ACLineSegment.gch> "0" ;
		<ACLineSegment.r> "1.501949" ;
		<ACLineSegment.r0> "1.531988" ;
		<ACLineSegment.shortCircuitEndTemperature> "80" ;
		<ACLineSegment.x> "5.92416" ;
		<ACLineSegment.x0> "0" ;
		<Conductor.length> "21.56994" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "7-12" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> ;
		<Equipment.EquipmentContainer> <urn:uuid:ea8245a5-bcde-f5d4-5252-118d01cf78ab> .

	<urn:uuid:e3594ff5-8006-4d03-aa82-f08cba77d4d4> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:0477feb7-c766-11e1-8775-005056c00008> .

	<urn:uuid:8d008fdb-f41c-4db5-859a-1fc5ccea1bcb> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:e3594ff5-8006-4d03-aa82-f08cba77d4d4> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:bed061b3-3663-40ad-956f-90cda64cbaab> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1150" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:e3594ff5-8006-4d03-aa82-f08cba77d4d4> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:b19bc945-cc51-4d77-8eaa-3f6afe2d9316> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1400" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:e3594ff5-8006-4d03-aa82-f08cba77d4d4> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:0468e382-c766-11e1-8775-005056c00008> rdf:type <ACLineSegment> ;
		<ACLineSegment.b0ch> "0" ;
		<ACLineSegment.bch> "0.0001629936" ;
		<ACLineSegment.g0ch> "0" ;
		<ACLineSegment.gch> "0" ;
		<ACLineSegment.r> "4.199184" ;
		<ACLineSegment.r0> "4.283167" ;
		<ACLineSegment.shortCircuitEndTemperature> "80" ;
		<ACLineSegment.x> "18.81792" ;
		<ACLineSegment.x0> "0" ;
		<Conductor.length> "38.52344" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "3-5" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> ;
		<Equipment.EquipmentContainer> <urn:uuid:1523a8ab-84b7-5990-6c01-36375d79bdb7> .

	<urn:uuid:2e30cdae-1471-4a4f-bcbe-674f1c0568e6> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:04742e24-c766-11e1-8775-005056c00008> .

	<urn:uuid:8a7e471e-0c7d-4e7b-820d-59ca391ad128> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:2e30cdae-1471-4a4f-bcbe-674f1c0568e6> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:751f81c5-bc0f-47d9-8bf1-215d33c20a33> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1150" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:2e30cdae-1471-4a4f-bcbe-674f1c0568e6> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:828ca44c-560b-4f94-b825-21e237285fae> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1400" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:2e30cdae-1471-4a4f-bcbe-674f1c0568e6> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:045ed162-c766-11e1-8775-005056c00008> rdf:type <ACLineSegment> ;
		<ACLineSegment.b0ch> "0" ;
		<ACLineSegment.bch> "0.0002330119" ;
		<ACLineSegment.g0ch> "0" ;
		<ACLineSegment.gch> "0" ;
		<ACLineSegment.r> "8.433216" ;
		<ACLineSegment.r0> "8.60188" ;
		<ACLineSegment.shortCircuitEndTemperature> "80" ;
		<ACLineSegment.x> "27.8784" ;
		<ACLineSegment.x0> "0" ;
		<Conductor.length> "119.375" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "3-12" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> ;
		<Equipment.EquipmentContainer> <urn:uuid:47cf580a-5e15-ef48-e878-21a79b1144ec> .

	<urn:uuid:0c765fbd-ec66-4bde-a61b-6ea1a664ecea> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:047a48a1-c766-11e1-8775-005056c00008> .

	<urn:uuid:c64cce0b-9c51-4283-8506-7d705fa03c6a> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:0c765fbd-ec66-4bde-a61b-6ea1a664ecea> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:00e770fb-802e-479b-ae76-a52f5614bc15> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1150" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:0c765fbd-ec66-4bde-a61b-6ea1a664ecea> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:c437e52c-43d7-4ae9-87ad-dc19396dc6ff> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1400" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:0c765fbd-ec66-4bde-a61b-6ea1a664ecea> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:04614263-c766-11e1-8775-005056c00008> rdf:type <ACLineSegment> ;
		<ACLineSegment.b0ch> "0" ;
		<ACLineSegment.bch> "1.20523E-05" ;
		<ACLineSegment.g0ch> "0" ;
		<ACLineSegment.gch> "0" ;
		<ACLineSegment.r> "0.306662" ;
		<ACLineSegment.r0> "0.3127952" ;
		<ACLineSegment.shortCircuitEndTemperature> "80" ;
		<ACLineSegment.x> "1.390435" ;
		<ACLineSegment.x0> "0" ;
		<Conductor.length> "34.09037" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "4-5" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> ;
		<Equipment.EquipmentContainer> <urn:uuid:5d48ed03-cfe3-d8d8-f342-c472df3a8732> .

	<urn:uuid:927edd7b-e6a3-4bfb-a9c7-3092b3b71449> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:04529c66-c766-11e1-8775-005056c00008> .

	<urn:uuid:a7e1bd6f-9c24-4c27-95f9-b2791300146c> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:927edd7b-e6a3-4bfb-a9c7-3092b3b71449> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:7ecdb83b-300c-47f9-a746-141b4e88f5d1> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1150" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:927edd7b-e6a3-4bfb-a9c7-3092b3b71449> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:2a95fb2b-6661-46e7-a9f6-fe63c1b7433c> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1400" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:927edd7b-e6a3-4bfb-a9c7-3092b3b71449> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:04642896-c766-11e1-8775-005056c00008> rdf:type <ACLineSegment> ;
		<ACLineSegment.b0ch> "0" ;
		<ACLineSegment.bch> "0.0001003214" ;
		<ACLineSegment.g0ch> "0" ;
		<ACLineSegment.gch> "0" ;
		<ACLineSegment.r> "3.641616" ;
		<ACLineSegment.r0> "3.714448" ;
		<ACLineSegment.shortCircuitEndTemperature> "80" ;
		<ACLineSegment.x> "11.98771" ;
		<ACLineSegment.x0> "0" ;
		<Conductor.length> "37.07665" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "4-11" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> ;
		<Equipment.EquipmentContainer> <urn:uuid:3b518c84-06ba-a557-3b88-b9963e609cdf> .

	<urn:uuid:c1ed2e34-2f01-49e7-af10-c39f9efe6154> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:0455f7c5-c766-11e1-8775-005056c00008> .

	<urn:uuid:c57e28bd-1572-426d-be4f-3485caf53d12> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:c1ed2e34-2f01-49e7-af10-c39f9efe6154> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:16d1fe69-1ba4-46ed-870c-952d884df26b> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1150" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:c1ed2e34-2f01-49e7-af10-c39f9efe6154> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:b1d87c24-e527-4174-aa04-cd0b9de271ea> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1400" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:c1ed2e34-2f01-49e7-af10-c39f9efe6154> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:04575750-c766-11e1-8775-005056c00008> rdf:type <PowerTransformer> ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "8-5" ;
		<Equipment.EquipmentContainer> <urn:uuid:046eafe6-c766-11e1-8775-005056c00008> .

	<urn:uuid:0472f5a7-c766-11e1-8775-005056c00008> rdf:type <PowerTransformerEnd> ;
		<PowerTransformerEnd.b> "0" ;
		<PowerTransformerEnd.connectionKind> "Y" ;
		<PowerTransformerEnd.b0> "0" ;
		<PowerTransformerEnd.phaseAngleClock> "0" ;
		<PowerTransformerEnd.ratedS> "400" ;
		<PowerTransformerEnd.g> "0" ;
		<PowerTransformerEnd.ratedU> "220" ;
		<PowerTransformerEnd.g0> "0" ;
		<PowerTransformerEnd.r> "0" ;
		<PowerTransformerEnd.r0> "0" ;
		<PowerTransformerEnd.x> "12.9228" ;
		<PowerTransformerEnd.x0> "0" ;
		<TransformerEnd.endNumber> "1" ;
		<TransformerEnd.grounded> "false" ;
		<IdentifiedObject.name> "8-5" ;
		<PowerTransformerEnd.PowerTransformer> <urn:uuid:04575750-c766-11e1-8775-005056c00008> ;
		<TransformerEnd.Terminal> <urn:uuid:04745533-c766-11e1-8775-005056c00008> ;
		<TransformerEnd.BaseVoltage> <urn:uuid:60ee59f3-5ed7-4551-b623-f4346554b22a> .

	<urn:uuid:5e06d999-c80d-40c9-902b-ef16b691f238> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:04745533-c766-11e1-8775-005056c00008> .

	<urn:uuid:d762d38b-9732-4cb1-9887-d7adca1867a7> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1312" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:5e06d999-c80d-40c9-902b-ef16b691f238> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:61e544bc-df04-4b97-8a18-5a8f66ae2ab7> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1508" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:5e06d999-c80d-40c9-902b-ef16b691f238> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:4109402d-315d-4c0e-8d0e-a7a277ad5608> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1837" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:5e06d999-c80d-40c9-902b-ef16b691f238> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:045eaa55-c766-11e1-8775-005056c00008> rdf:type <RatioTapChanger> ;
		<RatioTapChanger.tculControlMode> "volt" ;
		<RatioTapChanger.stepVoltageIncrement> "1.499999" ;
		<TapChanger.highStep> "9" ;
		<TapChanger.lowStep> "1" ;
		<TapChanger.ltcFlag> "false" ;
		<TapChanger.neutralStep> "2" ;
		<TapChanger.neutralU> "220" ;
		<TapChanger.normalStep> "1" ;
		<TapChanger.controlEnabled> "false" ;
		<TapChanger.step> "1" ;
		<IdentifiedObject.name> "8-5" ;
		<RatioTapChanger.TransformerEnd> <urn:uuid:0472f5a7-c766-11e1-8775-005056c00008> .

	<urn:uuid:0486cbc6-c766-11e1-8775-005056c00008> rdf:type <PowerTransformerEnd> ;
		<PowerTransformerEnd.b> "0" ;
		<PowerTransformerEnd.connectionKind> "Y" ;
		<PowerTransformerEnd.b0> "0" ;
		<PowerTransformerEnd.phaseAngleClock> "0" ;
		<PowerTransformerEnd.ratedS> "400" ;
		<PowerTransformerEnd.g> "0" ;
		<PowerTransformerEnd.ratedU> "132" ;
		<PowerTransformerEnd.g0> "0" ;
		<PowerTransformerEnd.r> "0" ;
		<PowerTransformerEnd.r0> "0" ;
		<PowerTransformerEnd.x> "0" ;
		<PowerTransformerEnd.x0> "0" ;
		<TransformerEnd.endNumber> "2" ;
		<TransformerEnd.grounded> "false" ;
		<IdentifiedObject.name> "8-5" ;
		<PowerTransformerEnd.PowerTransformer> <urn:uuid:04575750-c766-11e1-8775-005056c00008> ;
		<TransformerEnd.Terminal> <urn:uuid:046b2d74-c766-11e1-8775-005056c00008> ;
		<TransformerEnd.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> .

	<urn:uuid:86cd149c-9123-4daf-976f-7bc862080ee5> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "Ratings" ;
		<OperationalLimitSet.Terminal> <urn:uuid:046b2d74-c766-11e1-8775-005056c00008> .

	<urn:uuid:d75297d6-4951-46c6-aa29-4f518cd6e591> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "2186" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:86cd149c-9123-4daf-976f-7bc862080ee5> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:c4604ca3-6418-41f9-95f8-c7217db17e90> .

	<urn:uuid:7d97fc29-56b8-4cd3-924e-aa67d27306c8> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "2514" ;
		<IdentifiedObject.name> "ShortTerm" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:86cd149c-9123-4daf-976f-7bc862080ee5> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7747fcd0-2c9e-4cc7-ade6-29e7b3338e71> .

	<urn:uuid:23406b6a-ccc0-4233-a063-caf8238c5a4e> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "3061" ;
		<IdentifiedObject.name> "Emergency" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:86cd149c-9123-4daf-976f-7bc862080ee5> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:8a32b9fd-35f1-4dae-a9d0-e9344ed07958> .

	<urn:uuid:0447c6f6-c766-11e1-8775-005056c00008> rdf:type <LinearShuntCompensator> ;
		<LinearShuntCompensator.b0PerSection> "0" ;
		<LinearShuntCompensator.bPerSection> "0.0004592" ;
		<LinearShuntCompensator.g0PerSection> "0" ;
		<LinearShuntCompensator.gPerSection> "0" ;
		<ShuntCompensator.maximumSections> "10" ;
		<ShuntCompensator.nomU> "132" ;
		<ShuntCompensator.normalSections> "5" ;
		<ShuntCompensator.sections> "5" ;
		<RegulatingCondEq.controlEnabled> "true" ;
		<Equipment.aggregate> "false" ;
		<IdentifiedObject.name> "Olive SC" ;
		<RegulatingCondEq.RegulatingControl> <urn:uuid:c701959a-91c1-4a35-9a37-71fb790426ca> ;
		<Equipment.EquipmentContainer> <urn:uuid:044be5a3-c766-11e1-8775-005056c00008> .

	<urn:uuid:c701959a-91c1-4a35-9a37-71fb790426ca> rdf:type <RegulatingControl> ;
		<RegulatingControl.discrete> "true" ;
		<RegulatingControl.enabled> "true" ;
		<RegulatingControl.targetDeadband> "1" ;
		<RegulatingControl.targetValue> "133.676" ;
		<RegulatingControl.targetValueUnitMultiplier> "k" ;
		<IdentifiedObject.name> "Olive SC" ;
		<RegulatingControl.mode> "voltage" ;
		<RegulatingControl.Terminal> <urn:uuid:045e8340-c766-11e1-8775-005056c00008> .

	<urn:uuid:b831171a-601d-4007-a4f5-1dc75f3acfa3> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:e4248c3c-2067-4389-b657-976913c335e2> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:abf67f42-4245-4aa4-8a70-a93ebbf6f445> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:548fbf20-161f-4f26-8662-c5059393ffe6> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:4849a711-be86-4141-aa57-14de9a223911> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:7333db74-7101-4ada-a89d-2a04e01f16a6> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:c14541ea-5948-4978-87f7-df098661f0df> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:6634c3a7-488d-4066-9aad-c9e0e8e9f745> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:3c1ad5ec-be4b-4dc3-b50a-64130ac6d25f> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:2a5763de-3d99-4411-ab0c-15a1c5780e41> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:38648c04-41d4-4a3a-82aa-319ab24ae2e4> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:e1c77883-88fe-4a55-9aa2-b1a62a374e04> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:76e91f04-d086-4b81-9fb1-db9a509272e4> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:9d22a23c-375b-4722-a8c7-467f85a8006d> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:9b61b1b5-6ea7-43f0-8337-2ef5939e075f> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:2a058307-ead2-4581-9259-f2101bbf3c62> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:fdcca7ba-3946-45fd-a36b-0dc7eb0b5f42> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:95ca6534-9863-4aa3-98fc-a191ca13973a> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:30768c23-ea62-4732-8793-d19f5aa4bad3> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:0c08daa5-ef97-4cd4-b0a9-79746e43832f> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:93824de0-6fc2-4a6f-9878-8a1e86b71a7f> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:6a5b5e9d-b18a-4d87-863f-84eab3075a2d> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:b365accf-56be-411c-85ac-b8532c2c1f6d> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:e3594ff5-8006-4d03-aa82-f08cba77d4d4> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:b3034b71-8b61-4231-9d93-02915791d90e> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:2e30cdae-1471-4a4f-bcbe-674f1c0568e6> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:6cf83d54-2ace-4839-8b49-25b74124bb6c> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:0c765fbd-ec66-4bde-a61b-6ea1a664ecea> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:4b61ae44-af69-4465-8512-34dc31a38f1c> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:927edd7b-e6a3-4bfb-a9c7-3092b3b71449> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:1a878dee-0ece-46b9-8afd-94262b539855> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1000" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:c1ed2e34-2f01-49e7-af10-c39f9efe6154> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:f7187fd8-4235-4d8f-9e96-edad72c12128> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "1312" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:5e06d999-c80d-40c9-902b-ef16b691f238> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:6b54bded-e3a1-497c-9e0e-7c8036648eb5> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "2186" ;
		<IdentifiedObject.name> "Normal" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:86cd149c-9123-4daf-976f-7bc862080ee5> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:b05800c4-9744-45d8-8d9e-c1f39562e4fb> .

	<urn:uuid:048a9c58-c766-11e1-8775-005056c00008> rdf:type <VoltageLevel> ;
		<IdentifiedObject.name> "MNT132KV" ;
		<VoltageLevel.Substation> <urn:uuid:045beb3a-c766-11e1-8775-005056c00008> ;
		<VoltageLevel.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> .

	<urn:uuid:047eb571-c766-11e1-8775-005056c00008> rdf:type <VoltageLevel> ;
		<IdentifiedObject.name> "ETH132KV" ;
		<VoltageLevel.Substation> <urn:uuid:0476510a-c766-11e1-8775-005056c00008> ;
		<VoltageLevel.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> .

	<urn:uuid:044f6818-c766-11e1-8775-005056c00008> rdf:type <VoltageLevel> ;
		<IdentifiedObject.name> "ERB132KV" ;
		<VoltageLevel.Substation> <urn:uuid:0474f171-c766-11e1-8775-005056c00008> ;
		<VoltageLevel.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> .

	<urn:uuid:0488c79a-c766-11e1-8775-005056c00008> rdf:type <VoltageLevel> ;
		<IdentifiedObject.name> "WHI132KV" ;
		<VoltageLevel.Substation> <urn:uuid:048badc8-c766-11e1-8775-005056c00008> ;
		<VoltageLevel.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> .

	<urn:uuid:047eb579-c766-11e1-8775-005056c00008> rdf:type <VoltageLevel> ;
		<IdentifiedObject.name> "NAR132KV" ;
		<VoltageLevel.Substation> <urn:uuid:045dbff3-c766-11e1-8775-005056c00008> ;
		<VoltageLevel.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> .

	<urn:uuid:04605807-c766-11e1-8775-005056c00008> rdf:type <VoltageLevel> ;
		<IdentifiedObject.name> "RUS132KV" ;
		<VoltageLevel.Substation> <urn:uuid:04640189-c766-11e1-8775-005056c00008> ;
		<VoltageLevel.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> .

	<urn:uuid:047d07c9-c766-11e1-8775-005056c00008> rdf:type <VoltageLevel> ;
		<IdentifiedObject.name> "AND220KV" ;
		<VoltageLevel.Substation> <urn:uuid:046eafe6-c766-11e1-8775-005056c00008> ;
		<VoltageLevel.BaseVoltage> <urn:uuid:60ee59f3-5ed7-4551-b623-f4346554b22a> .

	<urn:uuid:044f4102-c766-11e1-8775-005056c00008> rdf:type <VoltageLevel> ;
		<IdentifiedObject.name> "WIN220KV" ;
		<VoltageLevel.Substation> <urn:uuid:046030f9-c766-11e1-8775-005056c00008> ;
		<VoltageLevel.BaseVoltage> <urn:uuid:60ee59f3-5ed7-4551-b623-f4346554b22a> .

	<urn:uuid:045c8779-c766-11e1-8775-005056c00008> rdf:type <VoltageLevel> ;
		<IdentifiedObject.name> "GON220KV" ;
		<VoltageLevel.Substation> <urn:uuid:0453add1-c766-11e1-8775-005056c00008> ;
		<VoltageLevel.BaseVoltage> <urn:uuid:60ee59f3-5ed7-4551-b623-f4346554b22a> .

	<urn:uuid:044be5a3-c766-11e1-8775-005056c00008> rdf:type <VoltageLevel> ;
		<IdentifiedObject.name> "AND132KV" ;
		<VoltageLevel.Substation> <urn:uuid:046eafe6-c766-11e1-8775-005056c00008> ;
		<VoltageLevel.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> .

	<urn:uuid:045d4ac5-c766-11e1-8775-005056c00008> rdf:type <VoltageLevel> ;
		<IdentifiedObject.name> "COM132KV" ;
		<VoltageLevel.Substation> <urn:uuid:044ca8f4-c766-11e1-8775-005056c00008> ;
		<VoltageLevel.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> .

	<urn:uuid:045beb3a-c766-11e1-8775-005056c00008> rdf:type <Substation> ;
		<IdentifiedObject.name> "Minas Tirith" ;
		<Substation.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:048badc8-c766-11e1-8775-005056c00008> rdf:type <Substation> ;
		<IdentifiedObject.name> "White Harbor" ;
		<Substation.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:046030f9-c766-11e1-8775-005056c00008> rdf:type <Substation> ;
		<IdentifiedObject.name> "Winterfell" ;
		<Substation.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:0474f171-c766-11e1-8775-005056c00008> rdf:type <Substation> ;
		<IdentifiedObject.name> "Erebor" ;
		<Substation.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:046eafe6-c766-11e1-8775-005056c00008> rdf:type <Substation> ;
		<IdentifiedObject.name> "Andúnië" ;
		<Substation.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:0476510a-c766-11e1-8775-005056c00008> rdf:type <Substation> ;
		<IdentifiedObject.name> "Ethring" ;
		<Substation.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:045dbff3-c766-11e1-8775-005056c00008> rdf:type <Substation> ;
		<IdentifiedObject.name> "Nargothrond" ;
		<Substation.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:044ca8f4-c766-11e1-8775-005056c00008> rdf:type <Substation> ;
		<IdentifiedObject.name> "Combe" ;
		<Substation.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:04640189-c766-11e1-8775-005056c00008> rdf:type <Substation> ;
		<IdentifiedObject.name> "Rushey" ;
		<Substation.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:0453add1-c766-11e1-8775-005056c00008> rdf:type <Substation> ;
		<IdentifiedObject.name> "Gondolin" ;
		<Substation.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:62b0f284-310d-4b24-b3e9-de366f5d0ee0> rdf:type <LoadResponseCharacteristic> ;
		<LoadResponseCharacteristic.exponentModel> "false" ;
		<LoadResponseCharacteristic.pConstantCurrent> "0" ;
		<LoadResponseCharacteristic.pConstantImpedance> "0" ;
		<LoadResponseCharacteristic.pConstantPower> "1" ;
		<LoadResponseCharacteristic.pVoltageExponent> "0" ;
		<LoadResponseCharacteristic.qConstantCurrent> "0" ;
		<LoadResponseCharacteristic.qConstantImpedance> "0" ;
		<LoadResponseCharacteristic.qConstantPower> "1" ;
		<LoadResponseCharacteristic.qVoltageExponent> "0" ;
		<IdentifiedObject.name> "NwCarlsl NegG LD" .

	<urn:uuid:9f54ecca-3b0d-4b55-8bce-9f0eb76bde1b> rdf:type <LoadResponseCharacteristic> ;
		<LoadResponseCharacteristic.exponentModel> "false" ;
		<LoadResponseCharacteristic.pConstantCurrent> "0" ;
		<LoadResponseCharacteristic.pConstantImpedance> "0" ;
		<LoadResponseCharacteristic.pConstantPower> "1" ;
		<LoadResponseCharacteristic.pVoltageExponent> "0" ;
		<LoadResponseCharacteristic.qConstantCurrent> "0" ;
		<LoadResponseCharacteristic.qConstantImpedance> "0" ;
		<LoadResponseCharacteristic.qConstantPower> "1" ;
		<LoadResponseCharacteristic.qVoltageExponent> "0" ;
		<IdentifiedObject.name> "Olive NegG LD" .

	<urn:uuid:fed4a332-bf5c-9991-b062-a2721b00b7ad> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for 2-12" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:40678b23-eb91-15cb-dda2-2610e0e019ec> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for 1-3" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:f6102a72-48ac-b2b3-322e-5d460755be84> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for 6-7" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:d0ebfe42-1ef9-f555-a8ad-2a9243e1d6eb> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for 5-11" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:01a32454-1398-54cb-6555-d6d0150f99cd> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for 8-30" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:9a9901c2-83a4-62e3-94e1-a77c7ff54c64> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for 5-6" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:ed1cb08a-b26d-aba6-a3f4-06301279f2e3> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for 1-2" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:29dbf6d0-0a46-9741-fdec-be99f242e5e1> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for 11-12" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:2c9fd9b1-87fa-d66a-d5fe-c6b9e2924a0f> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for 8-9" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:3e1d2381-2712-7769-e861-0f7505ed2da0> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for 9-10" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:c879d0a1-6043-ae0a-7cd4-1639678c30ad> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for 11-13" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:ea8245a5-bcde-f5d4-5252-118d01cf78ab> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for 7-12" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:1523a8ab-84b7-5990-6c01-36375d79bdb7> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for 3-5" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:47cf580a-5e15-ef48-e878-21a79b1144ec> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for 3-12" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:5d48ed03-cfe3-d8d8-f342-c472df3a8732> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for 4-5" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:3b518c84-06ba-a557-3b88-b9963e609cdf> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for 4-11" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .
}
INSERT {
	<urn:uuid:785f7cbc-2352-4c48-bfa8-de45d16ebb85> rdf:type <EquivalentNetwork> ;
		<IdentifiedObject.name> "EquivalentNetwork" .

	<urn:uuid:87462adb-83ea-4fa4-9f8a-474f359ffb86> rdf:type <EquivalentInjection> ;
		<EquivalentInjection.regulationCapability> "false" ;
		<EquivalentInjection.regulationStatus> "false" ;
		<EquivalentInjection.regulationTarget> "132" ;
		<EquivalentInjection.p> "0.4035962" ;
		<EquivalentInjection.q> "20.7598" ;
		<IdentifiedObject.name> "_EQ_Concord" ;
		<EquivalentEquipment.EquivalentNetwork> <urn:uuid:785f7cbc-2352-4c48-bfa8-de45d16ebb85> ;
		<Equipment.EquipmentContainer> <urn:uuid:04851e1b-c766-11e1-8775-005056c00008> .

	<urn:uuid:853f4045-9c83-4f3b-8037-2a31fb0a9ce2> rdf:type <Terminal> ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "NETerminal" ;
		<Terminal.ConductingEquipment> <urn:uuid:87462adb-83ea-4fa4-9f8a-474f359ffb86> .

	<urn:uuid:b58dade2-0ef7-466a-bef2-9b32c66105e7> rdf:type <EquivalentShunt> ;
		<EquivalentShunt.b> "0.001407856" ;
		<EquivalentShunt.g> "-6.877146E-05" ;
		<IdentifiedObject.name> "_NE_Concord" ;
		<EquivalentEquipment.EquivalentNetwork> <urn:uuid:785f7cbc-2352-4c48-bfa8-de45d16ebb85> ;
		<Equipment.EquipmentContainer> <urn:uuid:04851e1b-c766-11e1-8775-005056c00008> .

	<urn:uuid:26b55678-e1a8-4483-aebb-23ef71ff9ba0> rdf:type <Terminal> ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "NETerminal" ;
		<Terminal.ConductingEquipment> <urn:uuid:b58dade2-0ef7-466a-bef2-9b32c66105e7> .

	<urn:uuid:a8a1ad2c-003f-4c7c-ab8b-b70e0e261ee1> rdf:type <Terminal> ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "NETerminal" ;
		<Terminal.ConductingEquipment> <urn:uuid:a936cb85-b795-4ea7-b983-ab94743df11e> .

	<urn:uuid:cc07df7f-6772-40b4-ac1c-2bc32b931748> rdf:type <Terminal> ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "NETerminal" ;
		<Terminal.ConductingEquipment> <urn:uuid:a936cb85-b795-4ea7-b983-ab94743df11e> .

	<urn:uuid:1302e1fc-9a7a-4d14-b503-15d14149da98> rdf:type <OperationalLimitType> ;
		<OperationalLimitType.limitType> "patl" ;
		<OperationalLimitType.direction> "absoluteValue" ;
		<IdentifiedObject.name> "PATL" .

	<urn:uuid:5022a050-1c41-4d45-8199-e394a5480b52> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "_OLS__EQBranch_NE_ConcordTwinBrc" ;
		<OperationalLimitSet.Terminal> <urn:uuid:a8a1ad2c-003f-4c7c-ab8b-b70e0e261ee1> .

	<urn:uuid:b33922a2-058f-4d19-94b9-9c2fcfe1161a> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "43.73428" ;
		<IdentifiedObject.name> "_CL__EQBranch_NE_ConcordTwinBrch" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:5022a050-1c41-4d45-8199-e394a5480b52> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:1302e1fc-9a7a-4d14-b503-15d14149da98> .

	<urn:uuid:a936cb85-b795-4ea7-b983-ab94743df11e> rdf:type <EquivalentBranch> ;
		<EquivalentBranch.negativeR12> "5.375715" ;
		<EquivalentBranch.negativeR21> "5.375715" ;
		<EquivalentBranch.negativeX12> "16.92245" ;
		<EquivalentBranch.negativeX21> "16.92245" ;
		<EquivalentBranch.positiveR12> "5.375715" ;
		<EquivalentBranch.positiveR21> "5.375715" ;
		<EquivalentBranch.positiveX12> "16.92245" ;
		<EquivalentBranch.positiveX21> "16.92245" ;
		<EquivalentBranch.r> "5.375715" ;
		<EquivalentBranch.r21> "5.375715" ;
		<EquivalentBranch.x> "16.92245" ;
		<EquivalentBranch.x21> "16.92245" ;
		<EquivalentBranch.zeroR12> "16.12714" ;
		<EquivalentBranch.zeroR21> "16.12714" ;
		<EquivalentBranch.zeroX12> "50.76735" ;
		<EquivalentBranch.zeroX21> "50.76735" ;
		<Equipment.aggregate> "true" ;
		<IdentifiedObject.name> "_EQBranch_NE_ConcordTwinBrch" ;
		<ConductingEquipment.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> ;
		<Equipment.EquipmentContainer> <urn:uuid:09025bfd-713f-d643-56ce-8cdc2404c7c7> .

	<urn:uuid:09025bfd-713f-d643-56ce-8cdc2404c7c7> rdf:type <Line> ;
		<IdentifiedObject.name> "Container for _EQBranch_NE_Conco" ;
		<Line.Region> <urn:uuid:0472a781-c766-11e1-8775-005056c00008> .

	<urn:uuid:a7a59008-12ed-418a-915e-c10ec6b58597> rdf:type <Terminal> ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "NETerminal" ;
		<Terminal.ConductingEquipment> <urn:uuid:95f4953a-7fc9-4f01-947b-2afce28baa52> .

	<urn:uuid:f8162d07-c251-49ef-898a-502b353df657> rdf:type <Terminal> ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "NETerminal" ;
		<Terminal.ConductingEquipment> <urn:uuid:95f4953a-7fc9-4f01-947b-2afce28baa52> .

	<urn:uuid:2deb749f-b315-4f4d-b4c8-050ec522aebe> rdf:type <OperationalLimitType> ;
		<OperationalLimitType.limitType> "patl" ;
		<OperationalLimitType.direction> "absoluteValue" ;
		<IdentifiedObject.name> "PATL" .

	<urn:uuid:ea356fde-64ea-48c0-b821-a98743215f98> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "_OLS__T_NE_ConcordSorenson2" ;
		<OperationalLimitSet.Terminal> <urn:uuid:a7a59008-12ed-418a-915e-c10ec6b58597> .

	<urn:uuid:d0a558bb-9c80-49fd-a9f9-74bfd5c8719d> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "9999" ;
		<IdentifiedObject.name> "_CL__T_NE_ConcordSorenson2" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:ea356fde-64ea-48c0-b821-a98743215f98> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:2deb749f-b315-4f4d-b4c8-050ec522aebe> .

	<urn:uuid:95f4953a-7fc9-4f01-947b-2afce28baa52> rdf:type <PowerTransformer> ;
		<Equipment.aggregate> "true" ;
		<IdentifiedObject.name> "_T_NE_ConcordSorenson2" ;
		<Equipment.EquipmentContainer> <urn:uuid:045ab2b4-c766-11e1-8775-005056c00008> .

	<urn:uuid:51908614-1bb3-4499-bc56-c0bbe277421e> rdf:type <PowerTransformerEnd> ;
		<PowerTransformerEnd.b> "0" ;
		<PowerTransformerEnd.connectionKind> "Y" ;
		<PowerTransformerEnd.b0> "0" ;
		<PowerTransformerEnd.ratedS> "9999" ;
		<PowerTransformerEnd.g> "0" ;
		<PowerTransformerEnd.ratedU> "132" ;
		<PowerTransformerEnd.g0> "0" ;
		<PowerTransformerEnd.r> "18.05287" ;
		<PowerTransformerEnd.r0> "54.15862" ;
		<PowerTransformerEnd.x> "140.6982" ;
		<PowerTransformerEnd.x0> "422.0945" ;
		<TransformerEnd.endNumber> "2" ;
		<IdentifiedObject.name> "_T_NE_ConcordSorenson2_TW1" ;
		<PowerTransformerEnd.PowerTransformer> <urn:uuid:95f4953a-7fc9-4f01-947b-2afce28baa52> ;
		<TransformerEnd.Terminal> <urn:uuid:a7a59008-12ed-418a-915e-c10ec6b58597> ;
		<TransformerEnd.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> .

	<urn:uuid:28794c47-a6e2-4cdd-8942-9ff681e713b6> rdf:type <PowerTransformerEnd> ;
		<PowerTransformerEnd.b> "0" ;
		<PowerTransformerEnd.connectionKind> "Y" ;
		<PowerTransformerEnd.b0> "0" ;
		<PowerTransformerEnd.ratedS> "9999" ;
		<PowerTransformerEnd.g> "0" ;
		<PowerTransformerEnd.ratedU> "220" ;
		<PowerTransformerEnd.g0> "0" ;
		<PowerTransformerEnd.r> "0" ;
		<PowerTransformerEnd.r0> "0" ;
		<PowerTransformerEnd.x> "0" ;
		<PowerTransformerEnd.x0> "0" ;
		<TransformerEnd.endNumber> "1" ;
		<IdentifiedObject.name> "_T_NE_ConcordSorenson2_TW2" ;
		<PowerTransformerEnd.PowerTransformer> <urn:uuid:95f4953a-7fc9-4f01-947b-2afce28baa52> ;
		<TransformerEnd.Terminal> <urn:uuid:f8162d07-c251-49ef-898a-502b353df657> ;
		<TransformerEnd.BaseVoltage> <urn:uuid:60ee59f3-5ed7-4551-b623-f4346554b22a> .

	<urn:uuid:c8188d7d-9a68-46d8-b698-60ffc6d81c81> rdf:type <EquivalentInjection> ;
		<EquivalentInjection.regulationCapability> "false" ;
		<EquivalentInjection.regulationStatus> "false" ;
		<EquivalentInjection.regulationTarget> "220" ;
		<EquivalentInjection.p> "-193.4198" ;
		<EquivalentInjection.q> "113.1109" ;
		<IdentifiedObject.name> "_EQ_Sorenson2" ;
		<EquivalentEquipment.EquivalentNetwork> <urn:uuid:785f7cbc-2352-4c48-bfa8-de45d16ebb85> ;
		<Equipment.EquipmentContainer> <urn:uuid:047b8123-c766-11e1-8775-005056c00008> .

	<urn:uuid:7f2f7c3b-845e-4286-9bf6-4ab08fb14782> rdf:type <Terminal> ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "NETerminal" ;
		<Terminal.ConductingEquipment> <urn:uuid:c8188d7d-9a68-46d8-b698-60ffc6d81c81> .

	<urn:uuid:28741455-a323-478f-9c1f-3bf616f93490> rdf:type <EquivalentShunt> ;
		<EquivalentShunt.b> "0.003759868" ;
		<EquivalentShunt.g> "0.0002214431" ;
		<IdentifiedObject.name> "_NE_Sorenson2" ;
		<EquivalentEquipment.EquivalentNetwork> <urn:uuid:785f7cbc-2352-4c48-bfa8-de45d16ebb85> ;
		<Equipment.EquipmentContainer> <urn:uuid:047b8123-c766-11e1-8775-005056c00008> .

	<urn:uuid:081e590c-b45b-49f7-a873-9bc71b474883> rdf:type <Terminal> ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "NETerminal" ;
		<Terminal.ConductingEquipment> <urn:uuid:28741455-a323-478f-9c1f-3bf616f93490> .

	<urn:uuid:a0abd5f4-aa6e-4af1-9a0c-5a82e5cca27c> rdf:type <Terminal> ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "NETerminal" ;
		<Terminal.ConductingEquipment> <urn:uuid:d12c7167-3b4c-483b-9bb0-40f8fe43dfc2> .

	<urn:uuid:20d29e1a-aedf-4943-a516-ac704a601dba> rdf:type <Terminal> ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "NETerminal" ;
		<Terminal.ConductingEquipment> <urn:uuid:d12c7167-3b4c-483b-9bb0-40f8fe43dfc2> .

	<urn:uuid:7057d2ce-f0a8-49a5-8413-1ccc9cec2b89> rdf:type <OperationalLimitType> ;
		<OperationalLimitType.limitType> "patl" ;
		<OperationalLimitType.direction> "absoluteValue" ;
		<IdentifiedObject.name> "PATL" .

	<urn:uuid:82a7848a-0564-4106-ad42-f653ead05aa8> rdf:type <OperationalLimitSet> ;
		<IdentifiedObject.name> "_OLS__T_NE_Sorenson2TwinBrch" ;
		<OperationalLimitSet.Terminal> <urn:uuid:a0abd5f4-aa6e-4af1-9a0c-5a82e5cca27c> .

	<urn:uuid:7606e7e4-1f94-4977-b8ee-3bdad1250234> rdf:type <CurrentLimit> ;
		<CurrentLimit.value> "9999" ;
		<IdentifiedObject.name> "_CL__T_NE_Sorenson2TwinBrch" ;
		<OperationalLimit.OperationalLimitSet> <urn:uuid:82a7848a-0564-4106-ad42-f653ead05aa8> ;
		<OperationalLimit.OperationalLimitType> <urn:uuid:7057d2ce-f0a8-49a5-8413-1ccc9cec2b89> .

	<urn:uuid:d12c7167-3b4c-483b-9bb0-40f8fe43dfc2> rdf:type <PowerTransformer> ;
		<Equipment.aggregate> "true" ;
		<IdentifiedObject.name> "_T_NE_Sorenson2TwinBrch" ;
		<Equipment.EquipmentContainer> <urn:uuid:0466e7ba-c766-11e1-8775-005056c00008> .

	<urn:uuid:4f7f2e9d-982d-4418-98b1-0163da84a51a> rdf:type <PowerTransformerEnd> ;
		<PowerTransformerEnd.b> "0" ;
		<PowerTransformerEnd.connectionKind> "Y" ;
		<PowerTransformerEnd.b0> "0" ;
		<PowerTransformerEnd.ratedS> "9999" ;
		<PowerTransformerEnd.g> "0" ;
		<PowerTransformerEnd.ratedU> "220" ;
		<PowerTransformerEnd.g0> "0" ;
		<PowerTransformerEnd.r> "5.45343" ;
		<PowerTransformerEnd.r0> "16.36029" ;
		<PowerTransformerEnd.x> "54.01061" ;
		<PowerTransformerEnd.x0> "162.0318" ;
		<TransformerEnd.endNumber> "1" ;
		<IdentifiedObject.name> "_T_NE_Sorenson2TwinBrch_TW1" ;
		<PowerTransformerEnd.PowerTransformer> <urn:uuid:d12c7167-3b4c-483b-9bb0-40f8fe43dfc2> ;
		<TransformerEnd.Terminal> <urn:uuid:a0abd5f4-aa6e-4af1-9a0c-5a82e5cca27c> ;
		<TransformerEnd.BaseVoltage> <urn:uuid:60ee59f3-5ed7-4551-b623-f4346554b22a> .

	<urn:uuid:725274ad-1328-43ce-9a7b-e2644a6e75b6> rdf:type <PowerTransformerEnd> ;
		<PowerTransformerEnd.b> "0" ;
		<PowerTransformerEnd.connectionKind> "Y" ;
		<PowerTransformerEnd.b0> "0" ;
		<PowerTransformerEnd.ratedS> "9999" ;
		<PowerTransformerEnd.g> "0" ;
		<PowerTransformerEnd.ratedU> "132" ;
		<PowerTransformerEnd.g0> "0" ;
		<PowerTransformerEnd.r> "0" ;
		<PowerTransformerEnd.r0> "0" ;
		<PowerTransformerEnd.x> "0" ;
		<PowerTransformerEnd.x0> "0" ;
		<TransformerEnd.endNumber> "2" ;
		<IdentifiedObject.name> "_T_NE_Sorenson2TwinBrch_TW2" ;
		<PowerTransformerEnd.PowerTransformer> <urn:uuid:d12c7167-3b4c-483b-9bb0-40f8fe43dfc2> ;
		<TransformerEnd.Terminal> <urn:uuid:20d29e1a-aedf-4943-a516-ac704a601dba> ;
		<TransformerEnd.BaseVoltage> <urn:uuid:c63f79cc-7953-4ab6-9fa6-f8c729bf895b> .

	<urn:uuid:2e9c8b54-3c5a-447a-9138-c0d34b731477> rdf:type <EquivalentInjection> ;
		<EquivalentInjection.regulationCapability> "false" ;
		<EquivalentInjection.regulationStatus> "false" ;
		<EquivalentInjection.regulationTarget> "132" ;
		<EquivalentInjection.p> "69.89783" ;
		<EquivalentInjection.q> "116.4923" ;
		<IdentifiedObject.name> "_EQ_TwinBrch" ;
		<EquivalentEquipment.EquivalentNetwork> <urn:uuid:785f7cbc-2352-4c48-bfa8-de45d16ebb85> ;
		<Equipment.EquipmentContainer> <urn:uuid:04479fe2-c766-11e1-8775-005056c00008> .

	<urn:uuid:0c771d78-c705-40ec-97ed-a0006196535e> rdf:type <Terminal> ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "NETerminal" ;
		<Terminal.ConductingEquipment> <urn:uuid:2e9c8b54-3c5a-447a-9138-c0d34b731477> .

	<urn:uuid:42c441e4-a236-4fd0-b3a7-c06b22552e2e> rdf:type <EquivalentShunt> ;
		<EquivalentShunt.b> "0.01029726" ;
		<EquivalentShunt.g> "-0.0002451482" ;
		<IdentifiedObject.name> "_NE_TwinBrch" ;
		<EquivalentEquipment.EquivalentNetwork> <urn:uuid:785f7cbc-2352-4c48-bfa8-de45d16ebb85> ;
		<Equipment.EquipmentContainer> <urn:uuid:04479fe2-c766-11e1-8775-005056c00008> .

	<urn:uuid:4c19ff4e-54c5-41a4-866a-3759ed651159> rdf:type <Terminal> ;
		<Terminal.phases> "ABC" ;
		<ACDCTerminal.connected> "true" ;
		<IdentifiedObject.name> "NETerminal" ;
		<Terminal.ConductingEquipment> <urn:uuid:42c441e4-a236-4fd0-b3a7-c06b22552e2e> .
}
